### ISSUE TITLE
Fix Solaris issues from Unicode

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.textstats#24]
We've now managed to migrate this Solaris error
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/quanteda.textstats-00check.html
from the main package to this package.

@koheiw I thought we'd fixed this? Can't we just skip cacheing altogether when it comes to Solaris?

**Comment by koheiw** [comment]
I think the issues is with Unicode, not caching, because emoji is supported since Unicode 8.0.

http://unicode.org/reports/tr51/#Versioning

But the Solaris 11.2 (it is 10 on CRAN) uses Unicode 6.0.

https://docs.oracle.com/cd/E36784_01/html/E36823/glmgn.html

I wonder why ICU bundle is not used by stringi on Solaris. Seems related to

https://github.com/gagolews/stringi/issues/262

We need to see the Unicode version on Solaris to determine the cause.

**Comment by koheiw** [comment]
I don't think the textstats package should have test-cache.R because it is quanteda's function. These tests are skipped on Solaris there.

**Comment by kbenoit** [comment]
True, but I seem to remember something about needing to include the tests, or it got counted against us in the codecov stats, since we basically copy those through assignment via e.g. `set_cache <- quanteda:::set_cache()`. 

But you’re right and if what I just said is correct, we should just disregard the codecov at this stage. We’re not chasing a record here after all.

**Comment by kbenoit** [comment]
v0.91 is up now and it has removed all cacheing functionality, but `textstat_summary()` still breaks Solaris. this indicates that the it must have something to do with the set of checks for character classes, probably the emoji check in 
https://github.com/quanteda/quanteda.textstats/blob/36966071d4983a658d13d22a7f76e0d0dbba2f42/R/textstat_summary.R#L71-L72

It's very tricky to test though without actually submitting to CRAN, since the rhub version seems to take this fine. But if it is this particular line, then we could solve the issue by just returning `NA` if we detect Solaris.
