### ISSUE TITLE
Keep cache functions in the core package

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#7]
This is not specifically for textstats, so better to keep in quanteda. The best place would  be `meta.R` or `cache.R`.
 
https://github.com/quanteda/quanteda.textstats/blob/bf61e1954553ca1385f7e5d9536e83619997e118/R/utils.R#L11-L49

**Comment by kbenoit** [comment]
Yes exactly, we need to figure out how to divide these between **quanteda** and **quanteda.textstats**. They are still in quanteda, since they are needed for caching after `summary()`, but they are here too. Even if we remove the `textstat_summary()` output from `quanteda::summary.corpus()`, we will still need in order to cache any summary info on the corpus overall, so I agree they belong in **quanteda**.

So some additional surgery is needed for this set of functions and for how `quanteda::summary.corpus()` will operate.
