### ISSUE TITLE
Aren't the function names too long?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#8]
`quanteda.textstats::textstat_keyness()` is very long. How about `quanteda.textstats::keyness()`? Outputs of textstat functions are more heterogeneous than of `dfm_*()`, `tokens_*()` and `corpus_*()`, so `textstat_` is just like a prefix.

**Comment by kbenoit** [comment]
1. It's part of the scheme of **quanteda** naming that we worked on so carefully, so that when all of the functions are compiled in say a single reference - and I would hope that they can continue to be at https://quanteda.io/reference/index.html - then it's clear what are models, what are stats, and what are plots. I think the rationale remains very strong to keep this organization. Remember all textstat functions return data.frames with either a document or a feature id column, plus the relevant statistical columns.

2. Renaming them would break a lot of code, why risk this because for a change of mind in our aesthetic approach?

3. Few people would probably use the `quanteda.textstats::textstat_keyness()` outside of package code, since we would be encouraging them to load **quanteda** and then **quanteda.textstats**. In fact that's designed to the _only_ change that the user will notice versus v2.
